# This is a basic workflow to help you get started with Actions

name: deploy-container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - main
    paths:
      # only run this workflow when we make a change to something inside
      - 'packages/container/**'

# set our execution environment to inside of our container directory
defaults:
  run:
    working-directory: packages/container

# actual jobs
jobs:
  build:
    # virtual machine
    runs-on: ubuntu-latest
    # actual commands
    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      
      - uses: chrislennon/action-aws=cli@v1.1
      # dist (after bulid)
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
