# This is a basic workflow to help you get started with Actions

name: deploy-marketing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - main
    paths:
      # only run this workflow when we make a change to something inside
      - 'packages/marketing/**'

# set the execution environment to inside of the container directory
defaults:
  run:
    working-directory: packages/marketing

# actual jobs
jobs:
  build:
    # virtual machine
    runs-on: ubuntu-latest
    # actual commands
    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: $ {{ secrets.PRODUCTION_DOMAIN }}
      
      - uses: shinyinc/action-aws-cli@v1.2
      # dist (after bulid)
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # create invalidation automatically
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/index.html"
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}